### ISSUE TITLE
how to train the model with custom images?

### ISSUE THREAD

**Issue by chen990627** [AutoHDR/CFFN#1]

**Comment by AutoHDR** [comment]
What is the kind of custom image? Could you be more specific?

**Comment by chen990627** [comment]
> What is the kind of custom image? Could you be more specific?

Thanks for reply! There are only children's facial images in my dataset.

**Comment by AutoHDR** [comment]
You can download a publicly available dataset with face normals, such as Photoface, and make a pre-trained model. Due to the inconsistent data distribution, you can use this code for refinement.

**Comment by chen990627** [comment]
> You can download a publicly available dataset with face normals, such as Photoface, and make a pre-trained model. Due to the inconsistent data distribution, you can use this code for refinement.

Thanks, does the dataset used in the refined stage only have images or can i use my dataset in the refined stage?

**Comment by AutoHDR** [comment]
If you have a coarse training model, it can be used for refinement in the second stage.
